### ISSUE TITLE
Memory Leak? Hide keeps consuming more memory the more project it had created.

### ISSUE THREAD

**Issue by wistuba** [hide-org/hide#127] opened 2024-10-05 10:00 UTC
I've started some larger experimentation using Hide where I use multiple processes and sequentially keep creating new projects. I've noticed that over time, the RAM consumption increases until I'm running out of memory.

My flow is very simple and basically does the following:

```
while True:  # technically using multiprocessing.Pool with 10 workers
  hc = Client()
  project = hc.create_project()
  # ...
  hc.delete_project(project)
```

The RAM is not consumed by the Python program. Killing it does not free the memory. Only killing hide does.

`delete_project` seems to correctly delete the docker containers.

My workaround for now: create a small set of projects, finish generation with them, and then kill hide. repeat until done.

**Comment by artmoskvin** [comment] 2024-10-05 12:22
Thanks for reporting! Just to confirm, deleting the project does not release the resources (ie memory)?

**Comment by wistuba** [comment] 2024-10-05 13:10
That's my understanding. At least the docker container change their status from "up" to "exited (137)". As far as I can tell, not calling `delete_project` will keep them in status "up".

Let me try to create and share a reproducible example.

**Comment by wistuba** [comment] 2024-10-05 18:22
The following script shows the mentioned behavior. Anything I'm missing?
```
from multiprocessing import Pool

from hide.client.hide_client import HideClient

from hide import model
from hide.devcontainer import ImageDevContainer


def process_func(i):
    print(i)
    hc = HideClient()
    project = hc.create_project(
        repository=model.Repository(url=f"https://github.com/awslabs/Renate"),
        devcontainer=ImageDevContainer(image="continuumio/miniconda3"),
        languages=[model.Language.PYTHON],
    )
    hc.delete_project(project)


def main():
    with Pool(10) as pool:
        pool.map(process_func, [i for i in range(999)])


if __name__ == "__main__":
    main()
```

**Comment by artmoskvin** [comment] 2024-10-05 19:24
The code looks legit. I'm trying to reproduce the problem locally now. Will get back soon.

**Comment by artmoskvin** [comment] 2024-10-05 20:11
I can confirm there's a memory leak. For some reason, LSP servers keep running, even though shutting them down is part of the project cleanup procedure. Killing hide solves the problem because hide is a parent process for all LSPs. I will inspect the code for bugs now.

**Comment by artmoskvin** [comment] 2024-10-05 21:39
Prepared a PR https://github.com/hide-org/hide/pull/128
We'll merge it tomorrow morning.

**Comment by wistuba** [comment] 2024-10-05 22:24
awesome, thank you!

**Comment by wistuba** [comment] 2024-10-06 10:30
I gave the new code a shot, but now I'm facing a new issue. Not sure this is a problem with the code or an issue on my side:

```hide.client.hide_client.HideClientError: Failed to list files: Failed to list files in project pMxG7cwcbO: failed to create gitignore matcher: open XXXX/.gitignore: too many open files in system```

there are a couple of other issues related to "too many open files"

**Comment by aleh-null** [comment] 2024-10-06 12:08
We will took into the new issue. 

Also we are continue working on issues related to LSP shut down. We are using [pyright](https://github.com/microsoft/pyright/tree/main). The server itself is implemented in TypeScript and is running in Node as a subprocess to a python process that starts it. This [PR](https://github.com/hide-org/hide/pull/129) uses process group to ensure that all processes in group are shut down.

**Comment by aleh-null** [comment] 2024-10-06 12:23
I suspect that `... too many open files in system` is related to missing `Close()`, let us know if this [PR](https://github.com/hide-org/hide/pull/130) fixes it.

**Comment by wistuba** [comment] 2024-10-06 13:19
#130 seems to have fixed the open files issue. This usually happened around 50 projects. now I made it beyond 100 before running OOM

**Comment by artmoskvin** [comment] 2024-10-06 17:51
We just merged #131 . The memory leak should be fixed now. Long story short, we did not shut LSP servers down properly. I reran the multiprocessing script and observed no memory leak. Let us know how it works for you @wistuba

**Comment by wistuba** [comment] 2024-10-06 18:01
awesome, I'll give it a shot right away

**Comment by wistuba** [comment] 2024-10-06 18:54
I can confirm that it works. Thank you!

**Closed** 2024-10-06 18:55 UTC
